export const START_LOGIN_REQUEST = "START_LOGIN_REQUEST";
export const STOP_LOGIN_REQUEST = "STOP_LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
