export const START_FETCHING_ALLNEWS = "START_FETCHING_ALLNEWS";
export const STOP_FETCHING_ALLNEWS = "STOP_FETCHING_ALLNEWS";
export const FETCHING_ALLNEWS_SUCCESS = "FETCHING_ALLNEWS_SUCCESS";
export const FETCHING_ALLNEWS_FAILURE = "FETCHING_ALLNEWS_FAILURE";
