export const START_FETCHING_PROFILE = "START_FETCHING_PROFILE";
export const STOP_FETCHING_PROFILE = "STOP_FETCHING_PROFILE";
export const FETCHING_PROFILE_SUCCESS = "FETCHING_PROFILE_SUCCESS";
export const FETCHING_PROFILE_FAILURE = "FETCHING_PROFILE_FAILURE";
